image: node:18.12.1

stages:
  - build
  - test
  - deploy
  - deployment tests

build website:
  stage: build
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
  artifacts:
    paths:
      - ./public

test artifact:
  stage: test
  image: alpine
  script:
    - grep -q "Gatsby" ./public/index.html

test website:
  stage: test
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby serve &
    - sleep 3
    - curl "http://localhost:9000" | grep -q "Gatsby"

deploy to surge:
  stage: deploy
  script:
    - npm install --global surge
    - surge --project ./public --domain manroeee.surge.sh

test deployment:
  stage: deployment tests
  image: alpine
  script: curl "https://manroeee.surge.sh/index.html" | grep -q "Gatsby"
